version: '2'
services:
    newappli-app:
        image: newappli
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://newappli-mysql:3306/newappli?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://newappli-elasticsearch:9200
        ports:
            - 8080:8080
    newappli-mysql:
        extends:
            file: mysql.yml
            service: newappli-mysql
    newappli-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: newappli-elasticsearch
